repositories:
  remote:
   - https://repo.maven.apache.org/maven2

artifacts:
  jsinterop_base: com.google.jsinterop:base:jar:1.0.0

  jsinterop_annotations: com.google.jsinterop:jsinterop-annotations:jar:2.0.0
  akasha: org.realityforge.akasha:akasha-gwt:jar:0.30

  javax_annotation: org.realityforge.javax.annotation:javax.annotation:jar:1.0.1
  jetbrains_annotations: org.realityforge.org.jetbrains.annotations:org.jetbrains.annotations:jar:1.7.0

  gwt_user: org.gwtproject:gwt-user:jar:2.10.0
  gwt_dev: org.gwtproject:gwt-dev:jar:2.10.0
